---
devcontainer_aws_sso:
  start_url: https://example.awsapps.com/start/#
  account_id: "123456789012"
  role_name: AdministratorAccess
  session_name: example-sso
  region: us-east-1

devcontainers:
  - name: rust-example
    primary_language: rust
    plugins:
      - cache_cargo
      - shell_history
    install_steps:
      - sudo apt update
      - sudo apt install -y --no-install-recommends default-jre-headless

  - name: python-example
    image: mcr.microsoft.com/devcontainers/python:3.10
    primary_language: python
    python_version: "3.10"
    plugins:
      - aws
      - cache_python
      - cache_ansible
      - shell_history
    install_steps:
      - sudo apt update
      - sudo apt install -y --no-install-recommends ansible

  - name: cloud-example
    image: mcr.microsoft.com/devcontainers/base:resolute
    primary_language: terraform
    plugins:
      - aws
      - cache_terraform
      - shell_history
    vscode_extensions:
      - ms-kubernetes-tools.vscode-kubernetes-tools
    features:
      ghcr.io/devcontainers/features/kubectl-helm-minikube:1:
        version: "1.34"
        helm: latest
        minikube: none

  - name: node-example
    primary_language: typescript
    plugins:
      - cache_node
      - shell_history
