---
- name: Check project extra .devcontainer source directory
  ansible.builtin.stat:
    path: "{{ [devcontainer_sync_extra_files_root, devcontainer_sync_target_name] | path_join }}"
  register: devcontainer_sync_extra_source

- name: Find project extra .devcontainer files
  ansible.builtin.find:
    paths: "{{ devcontainer_sync_extra_source.stat.path }}"
    file_type: file
    recurse: true
  register: devcontainer_sync_extra_files
  when: devcontainer_sync_extra_source.stat.isdir | default(false)

- name: Ensure project extra .devcontainer file directories exist
  ansible.builtin.file:
    path: >-
      {{
        [
          workspace_root,
          devcontainer_sync_target_root,
          '.devcontainer',
          item.path | relpath(devcontainer_sync_extra_source.stat.path) | dirname,
        ]
        | path_join
      }}
    state: directory
    mode: "0755"
  loop: "{{ devcontainer_sync_extra_files.files | default([]) }}"
  loop_control:
    label: "{{ item.path | relpath(devcontainer_sync_extra_source.stat.path) | dirname }}"
  when: (item.path | relpath(devcontainer_sync_extra_source.stat.path)) not in devcontainer_sync_managed_files

- name: Copy project extra .devcontainer files
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: >-
      {{
        [
          workspace_root,
          devcontainer_sync_target_root,
          '.devcontainer',
          item.path | relpath(devcontainer_sync_extra_source.stat.path),
        ]
        | path_join
      }}
    mode: preserve
    backup: "{{ devcontainer_sync_backup }}"
  no_log: true
  loop: "{{ devcontainer_sync_extra_files.files | default([]) }}"
  loop_control:
    label: "{{ item.path | relpath(devcontainer_sync_extra_source.stat.path) }}"
  when: (item.path | relpath(devcontainer_sync_extra_source.stat.path)) not in devcontainer_sync_managed_files
